'use strict';

let CONSTANTS = {};

CONSTANTS.SERVER = {
	ONE: 1
};

CONSTANTS.AVAILABLE_AUTHS = {
	USER: 'user',
	// ADMIN: 'admin'
};

CONSTANTS.PASSWORD_PATTER_REGEX = /^(?=.{6,})(?=.*[a-z])(?=.*[0-9])(?=.*[A-Z])(?=.*[@#$%^&+=]).*$/;

CONSTANTS.NORMAL_PROJECTION = { __v: 0, isDeleted: 0, createdAt: 0, updatedAt: 0 };

CONSTANTS.MESSAGES = require('./messages');

CONSTANTS.SECURITY = {
	JWT_SIGN_KEY: 'fasdkfjklandfkdsfjladsfodfafjalfadsfkads',
	BCRYPT_SALT: 8,
	STATIC_TOKEN_FOR_AUTHORIZATION: '58dde3df315587b279edc3f5eeb98145'
};

CONSTANTS.ERROR_TYPES = {
	DATA_NOT_FOUND: 'DATA_NOT_FOUND',
	BAD_REQUEST: 'BAD_REQUEST',
	MONGO_EXCEPTION: 'MONGO_EXCEPTION',
	ALREADY_EXISTS: 'ALREADY_EXISTS',
	FORBIDDEN: 'FORBIDDEN',
	INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
	UNAUTHORIZED: 'UNAUTHORIZED',
	SOCKET_ERROR: 'SOCKET_ERROR',
	INVALID_MOVE: 'invalidMove'
};

CONSTANTS.HTTP_REQUEST_STATUS_CODES = {
	SUCCESS: 200,
	BAD_REQUEST: 400,
	UN_AUTHORIZED: 401,
	INTERNAL_SERVER_ERROR: 500,
	DATA_NOT_FOUND: 404
};

CONSTANTS.LOGIN_TYPES = {
	NORMAL: 1,
	GOOGLE_PLAY: 2,
	GAME_CENTER: 3
};

CONSTANTS.EMAIL_TYPES = {
	ACCOUNT_REGISTERED: 1,
	FORGOT_PASSWORD: 2
};

CONSTANTS.EMAIL_SUBJECTS = {
	ACCOUNT_REGISTERED: 'Account registered successfully',
	FORGOT_PASSWORD: 'Reset your password'
};

CONSTANTS.EMAIL_CONTENTS = {
	ACCOUNT_REGISTERED: 'public/templates/account-registered.html',
	FORGOT_PASSWORD: 'public/templates/forgot-password.html'
};

CONSTANTS.SOCKET_EVENTS = {
	DISCONNECT: 'disconnect'
};

CONSTANTS.MAX_LIMITS_OF_USERS_FOR_SINGLE_ROOM = 4;



CONSTANTS.AVAILABLE_EXTENSIONS_FOR_FILE_UPLOADS = ['csv', 'png'];

CONSTANTS.PAGINATION = {
	DEFAULT_LIMIT: 10,
	DEFAULT_NUMBER_OF_DOCUMENTS_TO_SKIP: 0
};

// CONSTANTS.TEMPLATES = require('./templates');

CONSTANTS.GENDER = {
	OTHER: 0,
	MALE: 1,
	FEMALE: 2
}

module.exports = CONSTANTS;
